### ISSUE TITLE
symbolic link 'model' directory

### ISSUE THREAD

**Issue by jannaescur** [vrenkens/nabu#10]
Hi again!

When testing, one of the first things is creating the test directory and copy the config files. It is alright, but then it creates a symbolic link to the 'model' directory but it is not created properly, since it can not find it inside the created directory output_train/test. When opening it says "Symbolic link that points to nonexistent file"... any idea?

**Comment by vrenkens** [comment]
I have never encountered this error.. when you browse to the model directory in the test directory does it show you the files model.pkl, checkpoint etc. ?

**Comment by vrenkens** [comment]
Oh and do you point to the same experiments directory that you used for training?

**Comment by jannaescur** [comment]
Yes, it is the same directory I used for training! The 'test' directory is created and the database and test_evaluator config files are copied. But I cannot even browse inside the 'model' directory...

![image](https://user-images.githubusercontent.com/22589206/34717447-6e4461ac-f533-11e7-8c9b-d95a7c3ea82f.png)

**Comment by vrenkens** [comment]
Hm, stange... Could you show me the output of 'ls -l'?

**Comment by jannaescur** [comment]
![image](https://user-images.githubusercontent.com/22589206/34717938-172099e8-f535-11e7-9e8e-ed811b9e6afb.png)

**Comment by vrenkens** [comment]
I think the problem is that you are using a relative path. The expdir path should be absolute (I should add this t the README :) ). Could you try your test command again with an absolute path?

**Comment by jannaescur** [comment]
yes!! it works! thanks!!
