### ISSUE TITLE
results tensorboard 

### ISSUE THREAD

**Issue by jannaescur** [vrenkens/nabu#13]
I am trying to see the outputs with Tensorboard. Do you know why I get two output events?

**Comment by vrenkens** [comment]
I don't understand the question... Which outputs would you like to see?

**Comment by jannaescur** [comment]
the training and validation loss, but the thing is that I get two outputs and in each one the graphs are different.

![image](https://user-images.githubusercontent.com/22589206/35151397-706f6eb6-fd1e-11e7-8052-bc5d2f84276e.png)

**Comment by vrenkens** [comment]
That is strange.. Have you done multiple experiments with the same expdir while tensorboard is running?
