### ISSUE TITLE
Character Error rate (CER) or Phoneme Error Rate (PER) ?

### ISSUE THREAD

**Issue by xavigiro** [vrenkens/nabu#15]
Hi Vincent,

this is [Xavier Giro](https://imatge.upc.edu/web/people/xavier-giro), one of Janna's advisors at UPC. First of all, I would like to thank you for the valuable support you are providing Janna during her bachelor thesis.

I am discussing with Janna regarding the metric she is using to evaluate the results, which I understand that it computed by your scripts. You refer to this metric as Character Error rate (CER), while the literature that we have read normally talks about Phoneme Error Rate (PER). This later option actually makes more sense to me as I understand that the TIMIT dataset provides phonetic transcriptions.

Could you please help us in sorting out

**Comment by vrenkens** [comment]
Hi Xavier,

Sorry for the confusion. I was talking about CER but I'm actually using PER. I just considered the phones to be my characters, but you are absolutely right to say that PER is more correct than CER.

**Comment by xavigiro** [comment]
Excellent. This solves our doubt. Thanks again for your very quick response :)
