### ISSUE TITLE
What is the relationship between this project and tfkaldi?

### ISSUE THREAD

**Issue by fanlu** [vrenkens/nabu#16]

**Comment by vrenkens** [comment]
I created tfkaldi first to use tenorflow together with Kaldi. Next I created Nabu to do sequence to sequence learning. So at first they were completely seperate, but now I added functionality to Nabu to do be able to work with Kaldi with some extra effort. So normally Nabu can do what tfkaldi does and much more.

**Comment by fanlu** [comment]
Thank you for your replay
