### ISSUE TITLE
module can't find

### ISSUE THREAD

**Issue by fanlu** [vrenkens/nabu#17]
When I use ./run data --recipe=config/recipes/DBLSTM/TIMIT/ --expdir=***
There are some missing module problems like
ImportError: cannot import name location_aware_attention
ImportError: cannot import name listener_ps
Is some of the features still not done?

**Comment by vrenkens** [comment]
That is strange... Are you using the most recent version?

**Comment by fanlu** [comment]
Yes, I use branch master, and run the script ./run data --recipe=config/recipes/DBLSTM/TIMIT/ --expdir=***. The project does not have these two python files, location_aware_attention.py listener_ps.py

**Comment by vrenkens** [comment]
I have found the listener_ps bug and fixed it. I can find no reference to location_aware_attention in my repository though. Can you pull the latest version and try again?

**Comment by fanlu** [comment]
nabu/neuralnetworks/models/ed_encoders/ed_encoder_factory.py
nabu/neuralnetworks/models/ed_encoders/__init__.py
nabu/neuralnetworks/components/__init__.py

**Comment by vrenkens** [comment]
This is the file in `nabu/neuralnetworks/components/__init__.py` in the master branch:

from . import hooks, ops, rnn_cell, layer, beam_search_decoder, constraints,\
attention

are you sure you have the most recent version?

**Comment by fanlu** [comment]
I've updated it again，and it's worked without exception.It's convenient if you push your wav.scp and everything need to run a demo. thank you very much

**Comment by vrenkens** [comment]
That would be difficult to do because the wav.scp should point to the location of the wav files in your file system. I can refer you to the [kaldi data preparation](http://kaldi-asr.org/doc/data_prep.html) to create these files.
