### ISSUE TITLE
Joint CTC-Attention

### ISSUE THREAD

**Issue by ghost** [vrenkens/nabu#22]
Hi Vincent,

First of all thank you for your work on this framework, I was looking for location attention-based mechanism implementation and I came across Nabu. Your design choices for adaptability make it really interesting for custom implementations.

Talking about implementations I saw you implemented a LAS network. As I wanted to do some experiments with Joint CTC-Attention decoding (https://arxiv.org/abs/1609.06773) I thought it could be quite interesting to implement it in your framework using your current LAS.
If you didn't read this paper before, the main differences with LAS are : 

 - An objective function based on logarithmic linear combinaison of CTC and attention objectives :
                    MTL = λ log p ctc (C|X) + (1 − λ) log p att (C|X)

 - A decoding approach for inference and training step based on a similar objective function :
                    Ĉ = arg max ∗ {λ log p ctc (C|X) +(1 − λ) log p att (C|X)}
      
To incorporate the CTC probabilities in the hypothesis score, the authors proposed two method : one using rescoring (two-pass, quite straightforward) and the other one decoding in one pass using an algorithm described in the paper.

I already wrote the custom loss function and most of the functions I need for decoding but I wanted to ask you some advices to keep it simple and not mess with the framework design.
In your opinion what are the classes I should focus on to do that?
For what I saw a custom loss function in loss_functions.py and a new Decoder class using beam search and CTC decoding should suffice or at least be a good starting point.

**Comment by vrenkens** [comment]
Hey, 

Thank you for your interest in Nabu :). The paper is very interesting, I assume the joint decoding comes from this paper: http://www.merl.com/publications/docs/TR2017-190.pdf?

As for implementing it you are right on the money :). There are a couple of things you will have to do:
- Implement an EDDecoder as part of your model that has 2 outputs, an attention-based output and a CTC output.
- Create a new loss function like you said.
- A new Decoder that combines CTC with beam-search decoder. You can start by just using the beam-search decoder with the new model. This way the CTC loss is considered to be used as regularisation. Then you can modify the beam search decoder to incorporate CTC.

If you have any more issues with implementation feel free to ask, I'm happy to help!

**Comment by ghost** [comment]
Yes that's right, the paper I linked is an early "version" of the paper you linked by the same main authors (Watanabe S., Hori T. & Kim. S.)!

I can focus on working on the joint-decoding implementation right now, it should be done in a few days I think :)
I'll go with the two-pass decoding at first and implement the one-pass algorithm after some early results.

As for issue, after trying the vanilla attention to check if everything was correct in the data preparation (I'm using librispeech and WSJ here), I encountered a problem using the LAS recipe for WSJ with windowed attention (standard recipe) : 

```
File "/home/fboye/tools/nabu/nabu/neuralnetworks/components/attention.py", line 335, in __init__
    name
File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 517, in __init__
    num_units, name="query_layer", use_bias=False, dtype=dtype),
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/core.py", line 112, in __init__
    **kwargs)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 121, in __init__
    self._dtype = None if dtype is None else dtypes.as_dtype(dtype).name
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/dtypes.py", line 624, in as_dtype
    raise TypeError("Cannot convert {} to a dtype. {}".format(type_value, e))
TypeError: Cannot convert LocationAwareAttention to a dtype. data type "LocationAwareAttention" not understood
```

It seems the Location attention you implemented couldn't be wrapped as an attention mechanism?

**Comment by vrenkens** [comment]
Hi, 
apparently it was a TF version 1.4 vs 1.5 issue that I somehow missed. I upgraded to TensorFlow 1.6 and solved the issue. The code has been pushed to the master branch.

**Comment by ghost** [comment]
Hi,

 I have to do some work on the decoding approach and further tests to be sure but everything seems to work.
Compared to what we said at the beginning I had to add as an extra a custom trainer and a custom model to accept the CTC+Att outputs. Nervertheless it was quite easy to implement, I reused most of your code to do the combinaison!

Out of curiosity, on another subject, why did you choose to use scipy.io.wav as sound file reader instead of soundfile? You could easily handle other formats such as flac for Librispeech for example.

Edit : I have some doubts concerning the best way to implement the two-pass approach in the framework.
Obviously the first pass can be done using the standard component beam_search.BeamSearchDecoder with seq2seq.dynamic_decode to get attention scores and using ctc_beam_search to get CTC probs, but for the rescoring pass I'm not so sure.
Should I create a new component with a rescoring flag + CTC probs and modify the step method to compute the rescoring when called a second time with flag=True through dynamic_decode or should I take another approach?
It seems to me with this approach the new component could replace the standard BeamSearchDecoder as it would be the same with a few modifications (two more instance variables + rescoring calculus when collecting hypotheses in expand_dims scope with flag raised to true). What do you think? I may be wrong here ^^

**Comment by vrenkens** [comment]
Hi,

I don't really see why you needed to implement another trainer. You can output CTC+att in a dictionary one element for each and use it like that in your loss function, right?

To be honest, I didn't consider a lot of alternatives for reading the sound files. What I implemented now works, so I just left it at that. If you have a better way feel free to implement it and submit a pull request.

As for implementing the two-pass decoding it, it looks pretty simple to me. The first pass is only using the attention part, so just use the already implemented BeamSeachDecoder to get a list of hypotheses. Then you get a CTC probability score for each hypothesis (using the standard tf.nn.ctc_loss function) and combine it with the attention score. The most practical way to implement this is to write a wrapper for the BeamSeachDecoder that uses the BeamSeachDecoder and adds the CTC functionality on top of it.

**Comment by ghost** [comment]
Without realizing it at first I was trying to do the one-pass algorithm through beam search as It was more logical compared to what I've already done. However I'm struggling on the two-pass decoding despite being simple.

I created a child class for BeamSearchDecoder and rewrote the __call__ function such as first pass is done through super where I recover the outputs ({sequences, length, scores, alignments}). 

For the second pass, if I understand correctly I should : 
 - Compute ctc_loss with logits and logits_seq_length + sequences and length as labels and labels_length.
 - Recompute att scores with previous computation and return outputs dict with updated scores.

Is it correct? Sorry if it seems rather trivial I don't really know why I'm struggling on that...

**Comment by vrenkens** [comment]
I wouldn't create a child function because as far as I understand the call method does not need to be modified. I would write a wrapper for it. Some pseudo code how I see it

```
class TwoPass(Decoder):
    def __init__(...):
        self.beam_search = BeamSearchDecoder(...)
        ...
    
    def __call__(....):
        hypotheses = self.beam_search(...)
        self.rescore(hypotheses)
        return hypotheses

    def rescore(self, hypotheses):
        for hypothesis in hypotheses:
              ctc_score = ctc_loss(hypothesis.sequence)
              hypothesis.score += lambda*ctc_score
```

This is of course not literally the code, but just to get the idea. I don't think you need to recompute the attention score, you can just use the one you get from the beam search.

**Comment by ghost** [comment]
Thanks for the pseudo code, except for the different approach it seems I understood correctly :)
The only difference being I weighted the attention score before adding weighted ctc score.


I thought I was messing somewhere because my loss during training was way off but my loss with standard LAS model doesn't make any sense too, going up and down at each iteration through multiple epoch.

Did you do some testing with Librispeech dataset already? I used the same recipe as TIMIT/WSJ with characters as units and 28 output dims (all characters + <space> + ' ) and the only modification I did was replacing scipy.io.wavfile.read(...)  with soundfile.read(...) to handle flac format (same inputs and outputs though) in audio_processor.py for data preparation. I checked generated features and text and I didn't see any problem here.

**Comment by vrenkens** [comment]
The loss going up and down each step is normal, especially in the beginning of training. This is because for longer utterances the loss is higher and the utterances are put in buckets of similar sequence length for efficiency reasons. So if a batch of long utterances is being processed the loss will be higher. 

I have not tried Librispeech yet, so I can't really comment on it.

**Comment by KunalDhawan** [comment]
Hi @dAklej and @vrenkens 
It would be really helpful if you could please add the joint CTC-Attention training script to main repository, if it would be possible.

Thank you
