### ISSUE TITLE
the model converge so slow

### ISSUE THREAD

**Issue by betterdam** [vrenkens/nabu#26]
Hi Vincent,
    First of all thank you for your work on this framework, i am so cofused about why the LAS converge so slow in my dataset(mandarin).  There are two pyramid layers(128 hidden cells) in encoder and two lstm layers(128-units) in decoder. It also applies vanilla attention.
**In epoch 1, the loss converge quickly, and curve is as follow:**
![image](https://user-images.githubusercontent.com/37864885/38018661-1b471cb2-32a8-11e8-841c-b2f261208363.png)
**In epoch 2, the loss converge so slow:**
![image](https://user-images.githubusercontent.com/37864885/38018675-27cf9ac2-32a8-11e8-9316-b66e3c157548.png)
**In epoch 3, the model is almost stable:**
![image](https://user-images.githubusercontent.com/37864885/38018683-2b34e69a-32a8-11e8-94a7-55ba97ca0325.png)
It's so sorry to disturb you, and if you could give me some advice about why the model converge so slow and have a large fluctuate, that would be better.
Have a good day!

betterdam

**Comment by vrenkens** [comment]
Hi Betterdam,

It is difficult to say. It is possible that this is caused by long sequences which can be difficult for LAS. You could try the windowed attention as in the WSJ LAS recipe?

Vincent

**Comment by fanlu** [comment]
Hi Betterdam,
Could you share your recipe to me?
