### ISSUE TITLE
speller decoder construction

### ISSUE THREAD

**Issue by riyijiye** [vrenkens/nabu#27]
Hi Vincent,

the input to your speller decoder is a dictionary of per-batch encoder outputs, and I do see when you create the attention mechanism, you do create one attention mechanism for each batch as below,

speller.py create_cell function

          if encoded is not None:
                #create the attention mechanism
                attention_mechanisms = [attention.factory(
                    conf=self.conf,
                    num_units=rnn_cell.output_size,
                    encoded=encoded[e],
                    encoded_seq_length=encoded_seq_length[e]
                ) for e in encoded]

but when you construct your training helper, you only pass in the first batch of your targets as below.
rnn_decoder.py

           expanded_targets = tf.pad(targets.values()[0], [[0, 0], [1, 0]],
                                  constant_values=output_dim-1)

           helper = tf.contrib.seq2seq.ScheduledEmbeddingTrainingHelper(
                    inputs=embedding(expanded_targets),
                    sequence_length=target_seq_length.values()[0]+1,
                    embedding=embedding,
                    sampling_probability=float(self.conf['sample_prob'])
                    )

later base decoder is constructed with rnn_cell wrapping above list of attention mechanism (cover the whole dictionary of batches of input) and above training helper.
rnn_decoder.py

         #create the decoder
         decoder = tf.contrib.seq2seq.BasicDecoder(
             cell=rnn_cell,
             helper=helper,
             initial_state=rnn_cell.zero_state(batch_size, tf.float32)
         )

I am wondering then when later decoder process the whole dictionary of batches, where decoder get targets information for all other batches than the first one?  

thanks,
Yan

**Comment by vrenkens** [comment]
Hi Yan,

The dictionary does not contain all batches. The batches are read and processed one by one inside the graph. 

The dictionary can contain multiple items if the encoder has multiple outputs, for example if you are processing multiple input stream as in the Watch, listen attend and spell architecture. For the LAS architecture only audio is used and encoded, so I can just take the first item in the dictionary which is the audio.

**Comment by riyijiye** [comment]
great! thanks Vincent!
