### ISSUE TITLE
your local BeamSearchDecoder implementation

### ISSUE THREAD

**Issue by riyijiye** [vrenkens/nabu#28]
Hi Vincent,

I have not read into code detail of your beam_search_decoder.py implementation. but I am just wondering, to achieve beam search decoding, what is the difference between using your BeamSearchDecoder and the one provided as tf.contrib.seq2seq.BeamSearchDecoder. with my rough understanding about tf.contrib.seq2seq module, It looks passing tf.contrib.seq2seq.BeamSearchDecoder into tf.contrib.seq2seq.dynamic_decode gives decoding results based on beam search algorithm.

thanks,
Harry

**Comment by vrenkens** [comment]
Hi Harry,

2 reasons why I have my own implementation:
1) When I first implemented this BeamSerachDecoder a long time ago, the contrib BeamSearchDecoder did not exist yet :)
2) Now that I have my own and it works I can do some custom stuff, like visualizing the attention. I tried doing the same thing with the contrib one but failed :).

Cheers

**Comment by riyijiye** [comment]
thanks Vincent!

by the way, I saw you have a timit_fisher config, is it for combined timit and fisher English corpus. if it is, do you mind sharing your best results for this?

thanks,
Harry

**Comment by vrenkens** [comment]
No it's not :s it was a project of a master student to do transfer learning with Elastic Weight Consolidation using the fisher information matrix, hence the name
