### ISSUE TITLE
phoneme vs. grapheme based?

### ISSUE THREAD

**Issue by mjhanphd** [vrenkens/nabu#35]
Hi.
If I'd like to run the LAS model to use graphemes (i.e. English characters) directly as output units, is it enough to set 'alphabet' in text_processor (plus all the other things that define 'alphabet') to "A B C ... Z"?
Thank you.

**Comment by vrenkens** [comment]
You should also adjust the datafiles fields in the database.conf. They should point to the files containing textual transcriptions

**Comment by vrenkens** [comment]
You should also create a text normalizer and use it in your text_processor. Look into nabu/processing/target_normalizers for more info :)
