### ISSUE TITLE
encoded and encoded_seq_length in attention.py

### ISSUE THREAD

**Issue by rzcwade** [vrenkens/nabu#36]
Hi Vincent,

I am trying to understand the way you defined tensors in attention.py. I saw in ed_decoder.py that you defined encoded as a dictionary of [batch_size x time x ...] tensors. Could you please clarify a little more about why it's a dictionary and what is ... for?

Thank you!

**Comment by vrenkens** [comment]
It is a dictionary to allow multiple sets of encoded features. Say that you are processing audiovisual information and you have an encoder for the video stream and one for the audio stream. The dictionary will then have two elements, one for each stream.

**Comment by rzcwade** [comment]
I see. Thanks, Vincent!
