### ISSUE TITLE
pBLSTM not implemented for LAS/WSJ recipe?

### ISSUE THREAD

**Issue by rzcwade** [vrenkens/nabu#37]
Hi Vincent,

I tried your recipe for LAS/WSJ and initially I thought it was meant for pyramidal BLSTM implementation.
 
However, I found out that in the "neuralnetworks/models/ed_encoders/dblstm.py" you called for layer.blstm() instead of layer.pblstm() (line 46). 

Did you mean to implement just the regular 2-layer BLSTM listener for this recipe, or is it a typo and it's supposed to be pBLSTM? 

Thank you!

**Comment by vrenkens** [comment]
I don't really remember, but I think both implementations are possible

**Comment by rzcwade** [comment]
Thanks for your response. I tried replacing blstm with listener in the encoder section of the model.cfg recipe and it worked fine.

Thanks!
