### ISSUE TITLE
Name of folder standart should be renamed to standard

### ISSUE THREAD

**Issue by AzizCode92** [vrenkens/nabu#40]
Under script/train.py [line 76](https://github.com/vrenkens/nabu/blob/dfcc3a20f399ec7a917729e3ea2d424600b05acb/nabu/scripts/prepare_train.py#L76 ) , and knowing that we have defined the variable `computing` before as defined in [line 36 ](https://github.com/vrenkens/nabu/blob/dfcc3a20f399ec7a917729e3ea2d424600b05acb/nabu/scripts/prepare_train.py#L36)
I think we should rename the folder standart to standard so the line 76 would not through errors.

**Comment by vrenkens** [comment]
I think you are right, no idea how this got in. I'll change and push
