### ISSUE TITLE
Beam_search_decoder error of "list index out of range"

### ISSUE THREAD

**Issue by AzizCode92** [vrenkens/nabu#42]
I finished training my model. Tested it with no error but when I tried the  decoder part
I got an error of " list index out of range" caused by the  beam_search_decoder.py in  line 131
    text = ' '.join([self.alphabet[s] for s in sequence ])
The alphabet I used for the decoder is :   
 \<space\> a b c d e f g h i j k l m n o p q r s t u v w x y z \<unk\>

The error here is caused because the length of my alphabet is 28 and the sequence has a length of 200 so knowing that the two lists have no equal length, the error will be thrown.

**Comment by vrenkens** [comment]
Hi, which recipe are you using and and have you pulled the latest version? The error is not caused by the difference in length, but because of the model output dimension is different from the alphabet size.

**Comment by AzizCode92** [comment]
Yes, it was the last version of Nabu. I'm using the recipe LAS for the librispeech.

**Comment by AzizCode92** [comment]
Correct, looking back to the dim_output in my model I found it is 39 and the alphabet is 28 including the \<space\> and the \<unk\>.
I think I have to retrain the model again?
What would be the dim outpout of the model in this case please? 26 or 28 ?

**Comment by vrenkens** [comment]
I am afraid so, yes

**Comment by AzizCode92** [comment]
Have you worked with the librispeech dataset before, in this case what would be the alphabet?
How do you chose this parameter. 
thank you.

**Comment by vrenkens** [comment]
I have not. It depends what you want to do in terms of special characters and punctuation. You have to normalize your tekst using the normalizers such that the tekst only contains characters from your alphabet

**Comment by AzizCode92** [comment]
Thank you, I fixed the problem and I have the results on the Librispeech dataset with a WER = 4.81
Planning to prepare soon for a pull request to your work.
For those who are reading my comment, please consider that the dim_output of your model must be equal to the alphabet size.
Best,
Aziz
