### ISSUE TITLE
Clarification required for some methods

### ISSUE THREAD

**Issue by k-priyadarshi** [vrenkens/nabu#45]
Hey Vincent! Absolutely stunning work this! I needed some clarification regarding the data preparation part. Would you be able to help?
In database.conf for LAS/TIMIT recipe:
a.) #a space seperated list of files containing the data
datafiles = /path/to/train/wav.scp
--> What is the appropriate format of wav.scp file required?
--> As I am working with TIMIT dataset, what should the text files contain -  phoneme transcriptions or word transcriptions?

b.)  #the directory where the processed data is stored
dir = /path/to/features/train
--> In above line, does it mean "where the processed data WILL BE stored"?  or does it actually need features already computed? 

c) Are the wav.scp and text files required in this recipe the same as produced by KALDI?
It would be a great help if you reply.

**Comment by vrenkens** [comment]
Hi,

a and c: yes the wav.scp files are exactly the same as the ones used by KALDI.

b: Yes that is what I mean :)

Cheers,
Vincent

**Comment by k-priyadarshi** [comment]
Thank you Vincent! That's really helpful.
