### ISSUE TITLE
windowing attention

### ISSUE THREAD

**Issue by riyijiye** [vrenkens/nabu#48]
Hi Vincent,

I did not quite get the logic behind which you implemented windowing attention. is there a referring paper?

thanks,
harry

**Comment by riyijiye** [comment]
I think I got it.

**Comment by vrenkens** [comment]
Hi Harry,

No there is not. The reasoning is that there shouldn't be big jumps in the
attention. In some case this helped the the network to train, especially
with long sequences.

Cheers,
Vincent
