### ISSUE TITLE
processor config

### ISSUE THREAD

**Issue by jannaescur** [vrenkens/nabu#5]
When initializing 'audio_processor' it is called super() and in class "processor" at init it is picking the items inside 'processor', so it can not find 'max_length' cause it is inside 'features', not 'processor' in the file 'feature_processor.cfg'. Is it wrong or am I doing something wrong?
If I do self.conf = dict(conf.items('feature')) in 'audio_processor' after super() it works but I do not know if it is the solution.

Maybe the problem is that it is picking the 'feature_processor.cfg' when it should be 'text_processor.cfg'? It should make sense since in 'text_processor.cfg' there is a 'max_length' inside 'processor'... but the path to the processor config in 'database.cfg' is already written...

Thanks!

**Comment by vrenkens** [comment]
You are absolutely right. I moved the max length to the processor section. Tis should solve the issue.
Thanks for pointing it out!
