### ISSUE TITLE
CTC decoder results saving

### ISSUE THREAD

**Issue by rzcwade** [vrenkens/nabu#51]
Hi @vrenkens ,

I was trying out your ctc decoder (/nabu/neuralnetworks/decoders/ctc_decoder.py) and  ran into "ValueError: Shape must be rank 1 but is rank 2 for 'ctc_decoder/strided_slice_2' (op: 'StridedSlice') with input shapes: [?], [1,0], [1,0], [1]." 
in line 76: indices = np.where(outputs[o].indices[:, 0] == i)[0]

I have decoded results in this form:
SparseTensorValue(indices=array([[ 0,  0],
       [ 0,  1],
       [ 0,  2],
       ...,
       [15, 29],
       [15, 30],
       [15, 31]]), values=array([12,  5, 20, ..., 18, 21,  5], dtype=int32), dense_shape=array([ 16, 199])),

And I am trying to convert it back to label sequence.

Could you help understand how indices is represented here? I don't quite understand the sparse representation of the ctc decoder results. In particular, what does this outputs[o].indices[:,0] mean?

Thanks!

**Comment by vrenkens** [comment]
Hey, I’m on vacation now, so I probably won’t be getting to this this year
:s.Sorry!

**Comment by rzcwade** [comment]
Hi @vrenkens . Thanks for the heads up. Have a good vacation~

Thanks!

**Comment by vrenkens** [comment]
I haven't really looked at where the error is coming from.

The indices contain where in the matrix values are present. For example if you're sparse matrix is M than M[0, 1] = 12.

What the line is doing is taking all the indices where the first value is equal to i, meaning that we're taking the ith row out of the matrix.

**Comment by rzcwade** [comment]
Hi @vrenkens . Thanks for your feedback. I actually used 
tf.sparse_to_dense to convert the above to numpy array like tensor, which solved my problem. 

Thanks!
