### ISSUE TITLE
input pipeline

### ISSUE THREAD

**Issue by jannaescur** [vrenkens/nabu#6]
When training, I get data_queue_elements empty, because it calls get_names from input_pipeline and can not find the names in the setfile. Error: 20051112_210631_490_fsp-B-0 was not found in all sets of data, ignoring this example. (for all the names)

My "files[0]" are like this: '20051221_210452_840_fsp-B-0': '/.../out/features/train/data/file1197'.

What I understand is that it takes the name (20051221_210452_840_fsp-B-0) and then it looks for it in every setfile: 
files[0] ('20051221_210452_840_fsp-B-0': '/.../out/features/train/data/file1197') and files[1]
 ('20051118_210455_552_fsp-B-045682-046311-0': '/.../out/normalized/train/data/file117599')

So it should find it when looping in files[0] but not in files[1], but as 'allfound' turns false and it breaks, even if the name is found in files[0] it would never go on...
I don't really know if I am getting it right! What can be happening? Thanks

**Comment by vrenkens** [comment]
when you have multiple sets (for example inputs and targets) it will make sure that a data element occurs in both sets, so they are matched correctly. 

Meaning when you're training your network element A in the inputs is mapped to element A in the targets B to B etc. 

When training you should make sure you're input features and matching transcriptions have the same name in the setfiles, otherwise get_filenames won't be able to match them correctly.

**Comment by jannaescur** [comment]
The thing is that for every feature file I have multiple transcription files. For example, for the feature file
20050908_182943_22_fsp-A        /.../out/features/train/data/file0
I have a lot like these:
20050908_182943_22_fsp-A-051002-051235  /.../out/normalized/train/data/file133
20050908_182943_22_fsp-A-051250-051695  /.../out/normalized/train/data/file134

as you can see the names start as the feature file name but adding some numbers.
This output is created in the data preparation step following the database.conf. For the audio features I specify the path to the file 'wav.scp' and for the text features to the file 'text' as it's specified in the example file.
Should I have the same number of files of both features and transcriptions? Because then the problem is in these wav.scp and text files... but I have checked it and I am pretty sure that are OK. Maybe I am not using the right files?

**Comment by vrenkens** [comment]
Yes, you should have the same number of features and transcriptions, why are there multiple transcriptions for one feature file?

**Comment by jannaescur** [comment]
For what I understood these wav.scp and text files are the ones in Kaldi "format", right? 
So the file "text" contains the transcriptions of each utterance, and "wav.scp" contains the location for each of the audio files.
Then there is also the segments file that contains the start and end time for each utterance in an audio file.
So there are many utterances for an audio file, and the file 'text' contains the transcriptions of the utterances, thats why I get many more transcriptions (one per utterance) in 'text' than audio files (every file has many utterances) in 'wav.scp'.  
If "wav.scp" should contain a list of features not audio files, then I don't really know how to get it because I was following Kaldi structure... :(

**Comment by vrenkens** [comment]
It is not entirely Kaldi format, I don't really use a segments file. You can solve this issue bij segmenting your audio first using the segments file and then doing your dataprep.

**Comment by MartaCostaJussa** [comment]
could you point us to a database that is prepared to use your code?

**Comment by vrenkens** [comment]
For quick experiments I usually use TIMIT. You can just use the kaldi dataprep for most databases (like timit, librispeech, gp, ...). If there is a segments file you should pre-segment the audio.

**Comment by MartaCostaJussa** [comment]
Is there a free version of TIMIT? Could you point us to a free database that we could use?

**Comment by vrenkens** [comment]
librispeech is free (http://www.openslr.org/12)

**Comment by MartaCostaJussa** [comment]
thanks vincent! also... would it be a lot to ask to add the code on how to segment our audio so that we can use Fisher database?

**Comment by vrenkens** [comment]
I've added a script: nabu/scripts/segment_audio.py that should create a segments.scp file in your data directory which should be readable by Nabu. It has not been tested though. Can you test it and report back?

**Comment by vrenkens** [comment]
Make sure your datafiles field in the database.conf points to the created segments.scp file

**Comment by jannaescur** [comment]
it seems it worked!! I just needed to import sys :) thank you so much!

**Comment by vrenkens** [comment]
glad it worked :)
