### ISSUE TITLE
How to calculate the WER for LAS model

### ISSUE THREAD

**Issue by brijmohan** [vrenkens/nabu#7]
Hi,

I have trained the LAS model using 

```
run train --recipe=/path/to/recipe --expdir=/path/to/expdir
```

Could you please explain to me how to compute the WER over the test set? All I can see is the loss.

Thanks!

**Comment by vrenkens** [comment]
Hi,

You can do this with

`run test --recipe=/path/to/recipe --expdir=/path/to/expdir`

**Comment by brijmohan** [comment]
Hi @vrenkens ,

`test` gives me loss which I can't use for comparison with existing systems.

Instead I decode:
`run decode--recipe=/path/to/recipe --expdir=/path/to/expdir`

and then use `python nabu/scripts/wer.py <ref> </path/to/expdir>/decode/decoded`

This gives the actual WER. I might have pre-processed LAS output to join characters and get words before feeding it to the script.

Thanks!

**Comment by vrenkens** [comment]
The loss that the evaluator outputs at test time should be the WER if your using a decoder evaluator
