### ISSUE TITLE
Invalid Argument Error when training

### ISSUE THREAD

**Issue by jannaescur** [vrenkens/nabu#8]
When training I get this error:

tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [_oh y mi esposo tambi\303\251n_]

I don't think this is related to your code but maybe you can help us. The part in _italic_ (the transcription) changes everytime I try it. It is not a problem of Spanish characters because sometimes happens with sentences with only English characters. Any idea of what is going on?

**Comment by jannaescur** [comment]
maybe it is because the version of Tensorflow or some library? which one are you using?

**Comment by vrenkens** [comment]
Hi,

If I'm not mistaken this error is caused by the fact that not all characters in the transcription are defined in your alphabet. Could you double check?

Cheers

**Comment by vrenkens** [comment]
I'm using tf 1.4

**Comment by jannaescur** [comment]
you are right! thank you so much

**Comment by rzcwade** [comment]
Hi @jannaescur @vrenkens ,

I ran into the same issue when training on timit. How did you go about fixing the characters not defined in alphabet issue?

Thanks
