### ISSUE TITLE
Label value outside the valid range

### ISSUE THREAD

**Issue by jannaescur** [vrenkens/nabu#9]
InvalidArgumentError (see above for traceback): Received a label value of 48 which is outside the valid range of [0, 40).  Label values: 1 23 24 47 11 39 5 1 1 39 19 31 47 11 39 42 45 4 14.... (a large list of numbers)

do you have any idea of where can it come from? it is also when training. thanks!

**Comment by vrenkens** [comment]
You have to specify the output dimension in your model configuration. I think this is currently set to 39 in your file, but should be set to however many output symbols you have in your alphabet.
